# Generated by Django 4.1.6 on 2023-08-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_maps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maps',
        ),
        migrations.DeleteModel(
            name='regForCriteria',
        ),
        migrations.DeleteModel(
            name='uniqueCriteria',
        ),
        migrations.DeleteModel(
            name='wordToCriteria',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='content',
            new_name='crit_list',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.TextField(default='Hello World'),
        ),
        migrations.AddField(
            model_name='test',
            name='regs',
            field=models.TextField(default='Hello World'),
        ),
        migrations.AddField(
            model_name='test',
            name='unique_crits',
            field=models.TextField(default='Hello World'),
        ),
    ]
