# Generated by Django 4.1.6 on 2023-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_delete_maps_delete_regforcriteria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='f1',
            field=models.CharField(default='static/text/no_bracket_criteria.txt', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='f2',
            field=models.CharField(default='static/text/unique_criteria.txt', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='f3',
            field=models.CharField(default='static/text/regex_expressions.txt', max_length=100),
        ),
    ]
