# Generated by Django 4.1.6 on 2023-08-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_student_result_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='text',
            field=models.TextField(default='hello world', max_length=500000),
        ),
    ]
