# Generated by Django 4.1.6 on 2023-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_classroom_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='text',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='quiz.student'),
        ),
    ]
