# Generated by Django 4.1.6 on 2023-08-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_student_result_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='breakdown',
            field=models.TextField(default='none', max_length=500000),
        ),
        migrations.AddField(
            model_name='student',
            name='correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='crit_counter',
            field=models.TextField(default='none', max_length=500000),
        ),
        migrations.AddField(
            model_name='student',
            name='incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
