# Generated by Django 4.2.4 on 2023-08-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_student_breakdown_student_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='unnamed', max_length=100),
        ),
    ]
