# Generated by Django 4.2.4 on 2023-08-26 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_test_name'),
        ('quiz', '0021_alter_test_steps'),
    ]

    operations = [
    ]
