# Generated by Django 4.2.4 on 2023-08-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_merge_0020_alter_test_name_0021_alter_test_steps'),
        ('quiz', '0024_add_test_steps'),
    ]

    operations = [
    ]
